# Generated by Django 2.2.12 on 2020-05-12 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productType', models.CharField(max_length=255)),
                ('contactID', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('dueDate', models.DateTimeField()),
                ('lineAmountTypes', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField()),
                ('unitAmount', models.IntegerField()),
                ('accountCode', models.IntegerField()),
                ('discountRate', models.IntegerField()),
            ],
        ),
    ]
